directories:
  output: dist-electron
  buildResources: build
appId: com.curadesk.pm
productName: CuraDesk-PM
copyright: Copyright © 2026
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - package.json
asar: true
win:
  target:
    - portable
  icon: public/icon.png
mac:
  target:
    - dmg
  icon: public/icon.png
linux:
  target:
    - AppImage
electronVersion: 42.4.0
